Exception in thread ping:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 192, in test_ping
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte
Exception in thread shm1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 209, in test_shm1
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 0: invalid start byte
Exception in thread shm_write:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 228, in test_shm_write
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0: unexpected end of data
Exception in thread map_inexistent:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 275, in test_map_inexistent
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 0: invalid start byte
Exception in thread map1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 288, in test_map1
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 0: unexpected end of data
Exception in thread read_offset:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 301, in test_read_offset
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 0: invalid start byte
Exception in thread read_section:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 365, in test_read_section
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 0: invalid start byte
Exception in thread read_logical:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 434, in test_read_logical
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 0: invalid start byte
[1;35mTesting ping...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'PING'
Test score: 1 / 10
[1;35mTesting shm1...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10
[1;35mTesting shm_write...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10
[1;35mTesting map_inexistent...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'MAP_FILE'
[TESTER] sending string 'test_root/GRE4brzmEf7B.XvX'
Test score: 1 / 5
[1;35mTesting map1...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'MAP_FILE'
[TESTER] sending string 'test_root/1Z2tm7sMGl.sm2'
Test score: 1 / 5
[1;35mTesting read_offset...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10
[1;35mTesting read_section...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10
[1;35mTesting read_logical...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10

Total score: 8 / 70
Assignment grade: 11.43 / 100
Exception in thread ping:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 192, in test_ping
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 0: unexpected end of data
Exception in thread shm1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 209, in test_shm1
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 0: unexpected end of data
Exception in thread shm_write:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 228, in test_shm_write
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0: unexpected end of data
Exception in thread map_inexistent:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 275, in test_map_inexistent
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Exception in thread map1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 288, in test_map1
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte
Exception in thread read_offset:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 301, in test_read_offset
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte
Exception in thread read_section:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 365, in test_read_section
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 0: unexpected end of data
Exception in thread read_logical:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 514, in run
    sc = getattr(self, "test_" + self.name)(self.params)
  File "/hw/tester.py", line 434, in test_read_logical
    r = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte
[1;35mTesting ping...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'PING'
Test score: 1 / 10
[1;35mTesting shm1...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10
[1;35mTesting shm_write...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10
[1;35mTesting map_inexistent...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'MAP_FILE'
[TESTER] sending string 'test_root/GRE4brzmEf7B.XvX'
Test score: 1 / 5
[1;35mTesting map1...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'MAP_FILE'
[TESTER] sending string 'test_root/1Z2tm7sMGl.sm2'
Test score: 1 / 5
[1;35mTesting read_offset...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10
[1;35mTesting read_section...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10
[1;35mTesting read_logical...[0m
[TESTER] received string 'HELLO'
[TESTER] sending string 'CREATE_SHM'
[TESTER] sending number 3262703
Test score: 1 / 10

Total score: 8 / 70
Assignment grade: 11.43 / 100
