Exception in thread ping:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte
Exception in thread shm1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 0: invalid start byte
Exception in thread shm_write:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 0: invalid start byte
Exception in thread map_inexistent:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 0: unexpected end of data
Exception in thread map1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 0: invalid start byte
Exception in thread read_offset:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 0: unexpected end of data
Exception in thread read_section:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte
Exception in thread read_logical:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte
[1;35mTesting ping...[0m
Test score: 0 / 10
[1;35mTesting shm1...[0m
Test score: 0 / 10
[1;35mTesting shm_write...[0m
Test score: 0 / 10
[1;35mTesting map_inexistent...[0m
Test score: 0 / 10
[1;35mTesting map1...[0m
Test score: 0 / 10
[1;35mTesting read_offset...[0m
Test score: 0 / 10
[1;35mTesting read_section...[0m
Test score: 0 / 10
[1;35mTesting read_logical...[0m
Test score: 0 / 10

Total score: 0 / 80
[1;31mThere were some compilation warnings. A 10% penalty will be applied.[0m
Assignment grade: 0.00 / 100
Exception in thread ping:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 0: unexpected end of data
Exception in thread shm1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte
Exception in thread shm_write:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
Exception in thread map_inexistent:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
Exception in thread map1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 0: invalid start byte
Exception in thread read_offset:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte
Exception in thread read_section:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/hw/tester.py", line 511, in run
    s = self.readString()
  File "/hw/tester.py", line 148, in readString
    c = self.fdRes.read(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 0: unexpected end of data
[1;35mTesting ping...[0m
Test score: 0 / 10
[1;35mTesting shm1...[0m
Test score: 0 / 10
[1;35mTesting shm_write...[0m
Test score: 0 / 10
[1;35mTesting map_inexistent...[0m
Test score: 0 / 10
[1;35mTesting map1...[0m
Test score: 0 / 10
[1;35mTesting read_offset...[0m
Test score: 0 / 10
[1;35mTesting read_section...[0m
Test score: 0 / 10
[1;35mTesting read_logical...[0m
Test score: 0 / 10

Total score: 0 / 80
[1;31mThere were some compilation warnings. A 10% penalty will be applied.[0m
Assignment grade: 0.00 / 100
